[package]
name = "tree-sitter-wipple"
version = "0.0.0"
edition = "2021"
build = "bindings/rust/build.rs"

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1"
