[workspace]
resolver = "3"
members = [
    "compiler",
    "compiler/crates/*",
]

[workspace.lints.rust]
unused_crate_dependencies = "warn"
elided_lifetimes_in_paths = "deny"

[workspace.lints.clippy]
new_without_default = "allow"
too_many_arguments = "allow"
type_complexity = "allow"
