version: "3"

tasks:
    dev:
        cmds:
            - task: dev:visualizer
            - task: dev:app

    dev:visualizer:
        dir: visualizer
        cmds:
            - task: build:visualizer
              vars:
                  CLI_ARGS: "--dev"

    dev:app:
        dir: demo
        run: once
        cmds:
            - npm run dev -- --open

    build:
        cmds:
            - task: build:visualizer
            - task: build:app

    build:visualizer:
        dir: visualizer
        cmds:
            - wasm-pack build --target web {{.CLI_ARGS}}

    build:app:
        dir: demo
        cmds:
            - npm install
            - npm run build
