version: "3"

tasks:
    dev:
        cmds:
            - task: dev:app

    dev:app:
        deps:
            - dev:app:wasm
        dir: app
        cmds:
            - npm run dev -- --open

    dev:app:wasm:
        cmds:
            - task: build:app:wasm
              vars:
                  CLI_ARGS: "--dev"

    build:
        deps:
            - build:app

    build:app:
        deps:
            - build:app:wasm
        dir: app
        cmds:
            - npm install
            - npm run build

    build:app:wasm:
        dir: app/wasm
        cmds:
            - wasm-pack build --target web {{.CLI_ARGS}}
