version: "3"

tasks:
    dev:
        cmds:
            - task: dev:bindings
            - task: dev:app

    dev:bindings:
        cmds:
            - task: build:bindings
              vars:
                  CLI_ARGS: "--dev"

    dev:app:
        dir: demo/app
        run: once
        cmds:
            - npm run dev -- --open

    build:
        cmds:
            - task: build:bindings
            - task: build:app

    build:bindings:
        dir: demo/bindings
        cmds:
            - wasm-pack build --target web {{.CLI_ARGS}}

    build:app:
        dir: demo/app
        cmds:
            - npm install
            - npm run build
