version: "3"

tasks:
  dev:
    cmds:
      - task: dev:compiler
      - task: dev:app

  dev:compiler:
    dir: compiler
    cmds:
      - wasm-pack build --target bundler --no-opt

  dev:app:
    dir: demo
    run: once
    cmds:
      - npm run dev

  build:
    cmds:
      - task: build:compiler
      - task: build:app

  build:compiler:
    dir: compiler
    cmds:
      - wasm-pack build --target bundler

  build:app:
    dir: demo
    cmds:
      - npm install
      - npm run build
