[package]
name = "wipple-compiler-typecheck"
version = "0.0.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
ena = "0.14"
itertools = "0.14"
serde = { version = "1", features = ["derive"] }
