[package]
name = "wipple-compiler-lower"
version = "0.0.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
enum_delegate = "0.2"
wipple-compiler-syntax = { path = "../syntax" }
wipple-compiler-typecheck = { path = "../typecheck" }
