[package]
name = "wipple-visualizer-lower"
version = "0.0.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
enum_delegate = "0.2"
wipple-visualizer-syntax = { path = "../syntax" }
wipple-visualizer-typecheck = { path = "../typecheck" }
