[package]
name = "wipple-feedback"
version = "0.0.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow = "1"
itertools = "0.14"
regex = "1"
visualizer = { path = "../../../visualizer" }
wipple-db = { path = "../db" }
wipple-syntax = { path = "../syntax" }
