[package]
name = "visualizer"
version = "0.0.0"
edition = "2024"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
itertools = "0.14"
visualizer-db = { path = "crates/db" }
visualizer-typecheck = { path = "crates/typecheck" }
